-- RBAC 模块 RequestMapping 权限初始化脚本。
-- 依赖先执行 01_rbac.sql。
-- 相同 code 已存在时保持原记录不变。

INSERT INTO az_permission (create_time, code, name, target_identifier, target_qualifier, public_access) SELECT NOW(), 'POST:/authz/menu/create', 'POST:/authz/menu/create', '/authz/menu/create', 'POST', 1 WHERE NOT EXISTS (SELECT 1 FROM az_permission WHERE code = 'POST:/authz/menu/create');
INSERT INTO az_permission (create_time, code, name, target_identifier, target_qualifier, public_access) SELECT NOW(), 'POST:/authz/menu/remove/{id}', 'POST:/authz/menu/remove/{id}', '/authz/menu/remove/{id}', 'POST', 1 WHERE NOT EXISTS (SELECT 1 FROM az_permission WHERE code = 'POST:/authz/menu/remove/{id}');
INSERT INTO az_permission (create_time, code, name, target_identifier, target_qualifier, public_access) SELECT NOW(), 'POST:/authz/menu/tree', 'POST:/authz/menu/tree', '/authz/menu/tree', 'POST', 1 WHERE NOT EXISTS (SELECT 1 FROM az_permission WHERE code = 'POST:/authz/menu/tree');
INSERT INTO az_permission (create_time, code, name, target_identifier, target_qualifier, public_access) SELECT NOW(), 'POST:/authz/menu/update', 'POST:/authz/menu/update', '/authz/menu/update', 'POST', 1 WHERE NOT EXISTS (SELECT 1 FROM az_permission WHERE code = 'POST:/authz/menu/update');
INSERT INTO az_permission (create_time, code, name, target_identifier, target_qualifier, public_access) SELECT NOW(), 'POST:/authz/permission/cache/clear-all', 'POST:/authz/permission/cache/clear-all', '/authz/permission/cache/clear-all', 'POST', 1 WHERE NOT EXISTS (SELECT 1 FROM az_permission WHERE code = 'POST:/authz/permission/cache/clear-all');
INSERT INTO az_permission (create_time, code, name, target_identifier, target_qualifier, public_access) SELECT NOW(), 'POST:/authz/permission/create', 'POST:/authz/permission/create', '/authz/permission/create', 'POST', 1 WHERE NOT EXISTS (SELECT 1 FROM az_permission WHERE code = 'POST:/authz/permission/create');
INSERT INTO az_permission (create_time, code, name, target_identifier, target_qualifier, public_access) SELECT NOW(), 'POST:/authz/permission/list', 'POST:/authz/permission/list', '/authz/permission/list', 'POST', 1 WHERE NOT EXISTS (SELECT 1 FROM az_permission WHERE code = 'POST:/authz/permission/list');
INSERT INTO az_permission (create_time, code, name, target_identifier, target_qualifier, public_access) SELECT NOW(), 'POST:/authz/permission/remove/{id}', 'POST:/authz/permission/remove/{id}', '/authz/permission/remove/{id}', 'POST', 1 WHERE NOT EXISTS (SELECT 1 FROM az_permission WHERE code = 'POST:/authz/permission/remove/{id}');
INSERT INTO az_permission (create_time, code, name, target_identifier, target_qualifier, public_access) SELECT NOW(), 'POST:/authz/permission/update', 'POST:/authz/permission/update', '/authz/permission/update', 'POST', 1 WHERE NOT EXISTS (SELECT 1 FROM az_permission WHERE code = 'POST:/authz/permission/update');
INSERT INTO az_permission (create_time, code, name, target_identifier, target_qualifier, public_access) SELECT NOW(), 'POST:/authz/role-menu/list/{roleId}', 'POST:/authz/role-menu/list/{roleId}', '/authz/role-menu/list/{roleId}', 'POST', 1 WHERE NOT EXISTS (SELECT 1 FROM az_permission WHERE code = 'POST:/authz/role-menu/list/{roleId}');
INSERT INTO az_permission (create_time, code, name, target_identifier, target_qualifier, public_access) SELECT NOW(), 'POST:/authz/role-menu/update', 'POST:/authz/role-menu/update', '/authz/role-menu/update', 'POST', 1 WHERE NOT EXISTS (SELECT 1 FROM az_permission WHERE code = 'POST:/authz/role-menu/update');
INSERT INTO az_permission (create_time, code, name, target_identifier, target_qualifier, public_access) SELECT NOW(), 'POST:/authz/role-permission/list/{roleId}', 'POST:/authz/role-permission/list/{roleId}', '/authz/role-permission/list/{roleId}', 'POST', 1 WHERE NOT EXISTS (SELECT 1 FROM az_permission WHERE code = 'POST:/authz/role-permission/list/{roleId}');
INSERT INTO az_permission (create_time, code, name, target_identifier, target_qualifier, public_access) SELECT NOW(), 'POST:/authz/role-permission/update', 'POST:/authz/role-permission/update', '/authz/role-permission/update', 'POST', 1 WHERE NOT EXISTS (SELECT 1 FROM az_permission WHERE code = 'POST:/authz/role-permission/update');
INSERT INTO az_permission (create_time, code, name, target_identifier, target_qualifier, public_access) SELECT NOW(), 'POST:/authz/role/create', 'POST:/authz/role/create', '/authz/role/create', 'POST', 1 WHERE NOT EXISTS (SELECT 1 FROM az_permission WHERE code = 'POST:/authz/role/create');
INSERT INTO az_permission (create_time, code, name, target_identifier, target_qualifier, public_access) SELECT NOW(), 'POST:/authz/role/list', 'POST:/authz/role/list', '/authz/role/list', 'POST', 1 WHERE NOT EXISTS (SELECT 1 FROM az_permission WHERE code = 'POST:/authz/role/list');
INSERT INTO az_permission (create_time, code, name, target_identifier, target_qualifier, public_access) SELECT NOW(), 'POST:/authz/role/page', 'POST:/authz/role/page', '/authz/role/page', 'POST', 1 WHERE NOT EXISTS (SELECT 1 FROM az_permission WHERE code = 'POST:/authz/role/page');
INSERT INTO az_permission (create_time, code, name, target_identifier, target_qualifier, public_access) SELECT NOW(), 'POST:/authz/role/remove/{id}', 'POST:/authz/role/remove/{id}', '/authz/role/remove/{id}', 'POST', 1 WHERE NOT EXISTS (SELECT 1 FROM az_permission WHERE code = 'POST:/authz/role/remove/{id}');
INSERT INTO az_permission (create_time, code, name, target_identifier, target_qualifier, public_access) SELECT NOW(), 'POST:/authz/role/update', 'POST:/authz/role/update', '/authz/role/update', 'POST', 1 WHERE NOT EXISTS (SELECT 1 FROM az_permission WHERE code = 'POST:/authz/role/update');
INSERT INTO az_permission (create_time, code, name, target_identifier, target_qualifier, public_access) SELECT NOW(), 'POST:/authz/user-role/list/{userId}', 'POST:/authz/user-role/list/{userId}', '/authz/user-role/list/{userId}', 'POST', 1 WHERE NOT EXISTS (SELECT 1 FROM az_permission WHERE code = 'POST:/authz/user-role/list/{userId}');
INSERT INTO az_permission (create_time, code, name, target_identifier, target_qualifier, public_access) SELECT NOW(), 'POST:/authz/user-role/update', 'POST:/authz/user-role/update', '/authz/user-role/update', 'POST', 1 WHERE NOT EXISTS (SELECT 1 FROM az_permission WHERE code = 'POST:/authz/user-role/update');
